export const KEYWORD_CHANGED = 'KEYWORD_CHANGED'
export const FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST'
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS'
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE'
