export const search = {
  KEYWORD_CHANGED: 'KEYWORD_CHANGED',
  FETCH_VIDEOS_REQUEST: 'FETCH_VIDEOS_REQUEST',
  FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
  FETCH_VIDEOS_FAILURE: 'FETCH_VIDEOS_FAILURE',
  ITEM_SELECTED: 'ITEM_SELECTED',
}

export const createStation = {
  TITLE_CHANGED: 'TITLE_CHANGED',
  CREATE_STATION_REQUEST: 'CREATE_STATION_REQUEST',
  CREATE_STATION_SUCCESS: 'CREATE_STATION_SUCCESS',
  CREATE_STATION_FAILURE: 'CREATE_STATION_FAILURE',
}

export const login = {
  USER_LOGGED_IN: 'USER_LOGGED_IN',
}
